
from flask import session

def _cart():
    session.setdefault("bsm_cart", [])
    return session["bsm_cart"]

def _save_cart(cart):
    session["bsm_cart"] = cart
    session.modified = True

def clear_cart():
    _save_cart([])

def _video_price(video, package="original", price_id=None):
    try:
        if price_id:
            from app.models import VideoPricingPreset
            p = VideoPricingPreset.query.get(int(price_id))
            if p and getattr(p, "active", True):
                return float(p.price or 0)
    except Exception:
        pass
    try:
        if package == "edited":
            return float(getattr(video, "edited_price", 0) or 0)
        if package == "bundle":
            return float(getattr(video, "bundle_price", 0) or 0)
        return float(getattr(video, "original_price", 0) or 0)
    except Exception:
        return 0.0

def _boat_group_key(video):
    for attr in ("boat_group_key","boat_key","boat_id","boat_registration","registration","registration_number"):
        val = getattr(video, attr, None)
        if val:
            return str(val).strip().lower()
    creator_id = getattr(video, "creator_id", None) or getattr(video, "creator_profile_id", None) or "unknown"
    location = getattr(video, "location", None) or "unknown"
    date_val = getattr(video, "filmed_date", None) or getattr(video, "video_date", None) or getattr(video, "date", None) or ""
    time_val = getattr(video, "filmed_time", None) or getattr(video, "video_time", None) or getattr(video, "time", None) or ""
    return f"{creator_id}|{location}|{date_val}|{time_val}"

def add_video_to_cart(video, package="original", price_id=None, quantity=1):
    creator_id = getattr(video, "creator_id", None) or getattr(video, "creator_profile_id", None)
    item = {
        "item_type": "video",
        "video_id": getattr(video, "id", None),
        "creator_id": creator_id,
        "boat_key": _boat_group_key(video),
        "package": package,
        "price_id": price_id,
        "quantity": int(quantity or 1),
        "unit_price": float(_video_price(video, package, price_id) or 0),
        "discount_status": "none",
    }
    cart = _cart()
    cart.append(item)
    _save_cart(cart)
    return cart

def remove_item(index):
    cart = _cart()
    try:
        idx = int(index)
        if 0 <= idx < len(cart):
            cart.pop(idx)
            _save_cart(cart)
            return True
    except Exception:
        pass
    return False

def cart_groups_for_discount_review(cart=None):
    """
    Same-boat discount review appears only when the creator enabled it.
    """
    cart = cart if cart is not None else _cart()
    groups = {}
    for idx, item in enumerate(cart):
        if item.get("item_type") != "video":
            continue
        creator_id = item.get("creator_id")
        if not creator_discount_enabled_v428(creator_id):
            continue
        boat_key = item.get("boat_key")
        if not boat_key:
            continue
        key = (str(creator_id), str(boat_key))
        groups.setdefault(key, {"creator_id": creator_id, "boat_key": boat_key, "items": []})
        groups[key]["items"].append((idx, item))
    return [g for g in groups.values() if len(g["items"]) >= 2]


def cart_summary():
    cart = _cart()
    subtotal = sum(float(i.get("unit_price") or 0) * int(i.get("quantity") or 1) for i in cart)
    groups = cart_groups_for_discount_review(cart)
    return {"cart_id": current_cart_id(), "items": cart, "subtotal": round(subtotal,2), "total": round(subtotal,2), "pending_discount_review": False, "review_groups": groups, "count": len(cart)}

def build_cart_display_items():
    from app.models import Video
    out = []
    for idx, item in enumerate(_cart()):
        d = dict(item)
        d["index"] = idx
        if item.get("item_type") == "video":
            v = Video.query.get(item.get("video_id"))
            d["video"] = v
            d["title"] = "Boat video"
            d["location"] = getattr(v, "location", "") if v else ""
            d["thumbnail_url"] = _video_thumb_url(v)
        out.append(d)
    return out



def _video_thumb_url(video):
    if not video:
        return None
    # Prefer URLs already generated by the app.
    for attr in ("thumbnail_url", "public_thumbnail_url", "preview_thumbnail_url"):
        val = getattr(video, attr, None)
        if val:
            return str(val)
    key = getattr(video, "thumbnail_path", None) or getattr(video, "r2_thumbnail_key", None) or getattr(video, "thumb_key", None)
    if not key:
        return None
    key = str(key)
    if key.startswith("http"):
        return key
    # Existing app commonly serves R2 objects through /media/<key>
    return "/media/" + key.lstrip("/")



def current_cart_id():
    import secrets
    session.setdefault("bsm_cart_id", secrets.token_urlsafe(16))
    session.modified = True
    return session["bsm_cart_id"]


def cart_snapshot_for_order():
    return {"cart_id": current_cart_id(), "items": list(_cart()), "summary": cart_summary()}


def _creator_discount_enabled(creator_id):
    """
    Same-boat discount only appears when the creator has it enabled.
    Supports multiple possible setting field names; defaults to False.
    """
    if not creator_id:
        return False
    try:
        from app.models import CreatorProfile
        c = CreatorProfile.query.get(creator_id)
        if not c:
            return False
        for attr in (
            "second_video_discount_enabled",
            "same_boat_discount_enabled",
            "multi_video_discount_enabled",
            "discount_enabled",
            "enable_discount",
        ):
            if hasattr(c, attr):
                return bool(getattr(c, attr))
    except Exception:
        pass
    return False


def creator_discount_enabled_v428(creator_id):
    """
    Discount is OFF by default. It only turns on if creator explicitly enabled it.
    Supports common column names without breaking if columns do not exist.
    """
    if not creator_id:
        return False
    try:
        from app import db
        # Try creator_profile first
        try:
            row = db.session.execute(db.text("""
                SELECT *
                FROM creator_profile
                WHERE id=:cid OR user_id=:cid
                LIMIT 1
            """), {"cid": creator_id}).mappings().first()
        except Exception:
            db.session.rollback()
            row = None

        # Try user table as fallback
        if not row:
            try:
                row = db.session.execute(db.text("""
                    SELECT *
                    FROM "user"
                    WHERE id=:cid
                    LIMIT 1
                """), {"cid": creator_id}).mappings().first()
            except Exception:
                db.session.rollback()
                row = None

        if not row:
            return False

        enabled_keys = [
            "second_video_discount_enabled",
            "same_boat_discount_enabled",
            "multi_video_discount_enabled",
            "discount_enabled",
            "enable_discount",
            "clip_discount_enabled",
        ]
        for key in enabled_keys:
            if key in row:
                return bool(row[key])

        # If only percentage exists but no enabled flag, keep OFF to avoid showing discount by mistake.
        return False
    except Exception:
        try:
            db.session.rollback()
        except Exception:
            pass
        return False

